/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILoot, ILootInterface } from "../ILoot";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "loot",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "name",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "minLevelRequired",
            type: "uint256",
          },
          {
            internalType: "int8",
            name: "health",
            type: "int8",
          },
          {
            internalType: "int8",
            name: "speed",
            type: "int8",
          },
          {
            internalType: "int8",
            name: "strength",
            type: "int8",
          },
          {
            internalType: "int8",
            name: "defense",
            type: "int8",
          },
          {
            internalType: "uint8",
            name: "background",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "weapon",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "armor",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "boots",
            type: "uint8",
          },
        ],
        internalType: "struct ILoot.Loot",
        name: "loot",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ILoot__factory {
  static readonly abi = _abi;
  static createInterface(): ILootInterface {
    return new utils.Interface(_abi) as ILootInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ILoot {
    return new Contract(address, _abi, signerOrProvider) as ILoot;
  }
}
