import * as defenderJson from "./artifacts/contracts/DungeonDefenders/DungeonDefenders.sol/DungeonDefenders.json";
import * as gemsJson from "./artifacts/contracts/Gems.sol/Gems.json";
import * as stakingJson from "./artifacts/contracts/Staking.sol/Staking.json";
import * as lootJson from "./artifacts/contracts/Loot/Loot.sol/DungeonLoot.json";
import * as faucetJson from "./artifacts/contracts/Faucet.sol/GemsFaucet.json";
import { DungeonDefenders, DungeonLoot, Gems, GemsFaucet, Staking } from "./typechain";

export const DEFENDER_ABI = defenderJson.abi;
export const GEMS_ABI = gemsJson.abi;
export const STAKE_ABI = stakingJson.abi;
export const LOOT_ABI = lootJson.abi;
export const FAUCET_ABI = faucetJson.abi;

export const DEFENDER_BYTECODE = defenderJson.bytecode;
export const GEMS_BYTECODE = gemsJson.bytecode;
export const STAKE_BYTECODE = stakingJson.bytecode;
export const LOOT_BYTECODE = lootJson.bytecode;
export const FAUCET_BYTECODE = faucetJson.bytecode;

export type GemsContact = Gems;
export type DungeonDefendersContract = DungeonDefenders;
export type DungeonLootContract = DungeonLoot;
export type StakingContract = Staking;
export type GemsFaucetContract = GemsFaucet;

/////////////////////////////
////////AUTOGENERATED////////
/////////////////////////////
export const GEMS_CONTRACT_ADDRESS = '0x5FbDB2315678afecb367f032d93F642f64180aa3';
export const FAUCET_CONTRACT_ADDRESS = '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0';
export const LOOT_CONTRACT_ADDRESS = '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512';
export const DEFENDER_CONTRACT_ADDRESS = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9';
export const STAKE_CONTRACT_ADDRESS = '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9';