import * as defenderJson from "./artifacts/contracts/DungeonDefenders/DungeonDefenders.sol/DungeonDefenders.json";
import * as gemsJson from "./artifacts/contracts/Gems.sol/Gems.json";
import * as stakingJson from "./artifacts/contracts/Staking.sol/Staking.json";
import * as lootJson from "./artifacts/contracts/Loot/Loot.sol/DungeonLoot.json";
import * as faucetJson from "./artifacts/contracts/Faucet.sol/GemsFaucet.json";
import { DungeonDefenders, DungeonLoot, Gems, GemsFaucet, Staking } from "./typechain";

export const DEFENDER_ABI = defenderJson.abi;
export const GEMS_ABI = gemsJson.abi;
export const STAKE_ABI = stakingJson.abi;
export const LOOT_ABI = lootJson.abi;
export const FAUCET_ABI = faucetJson.abi;

export const DEFENDER_BYTECODE = defenderJson.bytecode;
export const GEMS_BYTECODE = gemsJson.bytecode;
export const STAKE_BYTECODE = stakingJson.bytecode;
export const LOOT_BYTECODE = lootJson.bytecode;
export const FAUCET_BYTECODE = faucetJson.bytecode;

export type GemsContract = Gems;
export type DungeonDefendersContract = DungeonDefenders;
export type StakingContract = Staking;
export type GemsFaucetContract = GemsFaucet;
export type DungeonLootContract = DungeonLoot;

/////////////////////////////
////////AUTOGENERATED////////
/////////////////////////////
export const GEMS_CONTRACT_ADDRESS = '0x2b74c043460B324d87046d766886421b459fbAd9';
export const FAUCET_CONTRACT_ADDRESS = '0x34f39d534626937aF4EF77459be44d760547b232';
export const LOOT_CONTRACT_ADDRESS = '0x20279Fc7f5a364b29D7A431876277D699206a31E';
export const DEFENDER_CONTRACT_ADDRESS = '0xED21A234105f7dbD42361afcb0eC83E630272991';
export const STAKE_CONTRACT_ADDRESS = '0xfBd3EA07A739f9eF58AA75671f128df2Dcf6bc8c';