import * as defenderJson from "./artifacts/contracts/DungeonDefenders/DungeonDefenders.sol/DungeonDefenders.json";
import * as gemsJson from "./artifacts/contracts/Gems.sol/Gems.json";
import * as stakingJson from "./artifacts/contracts/Staking.sol/Staking.json";
import * as lootJson from "./artifacts/contracts/Loot/Loot.sol/DungeonLoot.json";
import * as faucetJson from "./artifacts/contracts/Faucet.sol/GemsFaucet.json";
import { DungeonDefenders, DungeonLoot, Gems, GemsFaucet, Staking } from "./typechain";

export const DEFENDER_ABI = defenderJson.abi;
export const GEMS_ABI = gemsJson.abi;
export const STAKE_ABI = stakingJson.abi;
export const LOOT_ABI = lootJson.abi;
export const FAUCET_ABI = faucetJson.abi;

export const DEFENDER_BYTECODE = defenderJson.bytecode;
export const GEMS_BYTECODE = gemsJson.bytecode;
export const STAKE_BYTECODE = stakingJson.bytecode;
export const LOOT_BYTECODE = lootJson.bytecode;
export const FAUCET_BYTECODE = faucetJson.bytecode;

export type GemsContract = Gems;
export type DungeonDefendersContract = DungeonDefenders;
export type StakingContract = Staking;
export type GemsFaucetContract = GemsFaucet;
export type DungeonLootContract = DungeonLoot;

/////////////////////////////
////////AUTOGENERATED////////
/////////////////////////////
export const GEMS_CONTRACT_ADDRESS = '0xF931Bdd3931299520f5c164aF962C4cAa5216161';
export const FAUCET_CONTRACT_ADDRESS = '0x1578C0455d5D74b7F90D2B356bF32A10FB08350c';
export const LOOT_CONTRACT_ADDRESS = '0x414A0fc074B4C756c9d4ebd0e6bDaaFa6d4a348b';
export const DEFENDER_CONTRACT_ADDRESS = '0x950262532278CAA7f7A86146Ff9B93E0de193e3d';
export const STAKE_CONTRACT_ADDRESS = '0x93bF80c84A560208ca421C31B7C9E922e9432B7e';